### ISSUE TITLE
Condensed TODO

### ISSUE THREAD

**Issue by efe-efe** [efe-efe/efe-efe.github.io#1]
- [ ] Make fade in/translate animations to start when animated elements appears on the screen
- [ ] Add a better footer, with social account links, etc.
- [x] Implement auto hide for the navbar
- [ ] Improve experience section description and layout to make it more appealing
- [x] Add an animation or color change for when the user hovers the photo
- [ ] Add flags for the language selector
- [x] Remove the number from the CV button
- [x] Redesign sidebar
- [x] Change favicon
- [ ] Add credits to Brittany Chiang by linking to https://brittanychiang.com/
- [ ] Save the selected language in the storage so there is no need to change it every time 
- [ ] Resume should download based on localization
- [ ] Fix media queries for some resolutions
- [ ] Fix Resume link (getonboard link has a time to live 😢)
